import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const targetFile = resolve(".env.development.local");
const mode = process.argv[2];
const branchArg = process.argv[3];

const usage = `Usage:
  node scripts/supabase-env.mjs local
  node scripts/supabase-env.mjs branch [branch-name-or-id]

Writes .env.development.local for Next.js local development.
`;

if (!mode || mode === "--help" || mode === "-h") {
  console.log(usage);
  process.exit(0);
}

const executable = (name) => {
  if (process.platform === "win32" && name === "npx") {
    return "npx.cmd";
  }

  return name;
};

const run = (command, args) => {
  const result = spawnSync(executable(command), args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });

  if (result.status !== 0) {
    const detail = [result.stderr, result.stdout].filter(Boolean).join("\n").trim();
    throw new Error(detail || `${command} ${args.join(" ")} failed.`);
  }

  return result.stdout;
};

const currentBranch = () => run("git", ["branch", "--show-current"]).trim();

const parseEnv = (output) => {
  const entries = {};

  for (const rawLine of output.split(/\r?\n/)) {
    const line = rawLine.trim().replace(/^export\s+/, "");
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line);

    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    entries[key] = stripQuotes(rawValue.trim());
  }

  return entries;
};

const stripQuotes = (value) => {
  if (value.length < 2) {
    return value;
  }

  const quote = value[0];
  const last = value[value.length - 1];

  if ((quote === `"` || quote === `'`) && quote === last) {
    return value.slice(1, -1);
  }

  return value;
};

const pick = (entries, keys) => {
  for (const key of keys) {
    const value = entries[key]?.trim();

    if (value) {
      return value;
    }
  }
};

const getSourceEnv = () => {
  if (mode === "local") {
    return {
      label: "local Supabase Docker stack",
      values: parseEnv(run("npx", ["supabase", "status", "-o", "env"])),
    };
  }

  if (mode === "branch") {
    const branch = branchArg || currentBranch();

    if (!branch) {
      throw new Error("No branch name was provided and Git did not return one.");
    }

    return {
      label: `Supabase branch ${branch}`,
      values: parseEnv(run("npx", ["supabase", "branches", "get", branch, "-o", "env"])),
    };
  }

  throw new Error(usage);
};

const toAppEnv = ({ label, values }) => {
  const supabaseUrl = pick(values, [
    "NEXT_PUBLIC_SUPABASE_URL",
    "SUPABASE_URL",
    "API_URL",
  ]);
  const supabaseKey = pick(values, [
    "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_PUBLISHABLE_KEY",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "SUPABASE_ANON_KEY",
    "ANON_KEY",
  ]);
  const databaseUrl = pick(values, [
    "DATABASE_URL",
    "POSTGRES_URL",
    "DB_URL",
    "POSTGRES_URL_NON_POOLING",
  ]);

  const missing = [];

  if (!supabaseUrl) {
    missing.push("Supabase URL");
  }

  if (!supabaseKey) {
    missing.push("Supabase anon/publishable key");
  }

  if (!databaseUrl) {
    missing.push("Postgres connection string");
  }

  if (missing.length > 0) {
    throw new Error(
      `Could not derive ${missing.join(", ")} from ${label}. Available keys: ${Object.keys(values)
        .sort()
        .join(", ")}`,
    );
  }

  return {
    label,
    env: {
      NEXT_PUBLIC_SUPABASE_URL: supabaseUrl,
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: supabaseKey,
      NEXT_PUBLIC_SUPABASE_ANON_KEY: supabaseKey,
      SUPABASE_URL: supabaseUrl,
      SUPABASE_ANON_KEY: supabaseKey,
      DATABASE_URL: databaseUrl,
      POSTGRES_URL: databaseUrl,
    },
  };
};

const serialize = ({ label, env }) => {
  const lines = [
    "# Generated by scripts/supabase-env.mjs.",
    "# This file is gitignored and is loaded by Next.js during local development.",
    `# Source: ${label}`,
    "",
  ];

  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}="${value.replaceAll('"', '\\"')}"`);
  }

  lines.push("");

  return lines.join("\n");
};

try {
  const appEnv = toAppEnv(getSourceEnv());
  writeFileSync(targetFile, serialize(appEnv));

  console.log(`Wrote ${targetFile} from ${appEnv.label}.`);
  console.log(`Keys: ${Object.keys(appEnv.env).join(", ")}`);
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
